version: '3.9'

services:
        db:
                image: postgres:14-alpine
                volumes:
                        - db:/var/lib/postgresql/data
                        - ./infrastructure/db/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
                env_file:
                        - .env

        web:
                build: .
                image: area99_assessment:dharmy
                depends_on:
                        - db
                ports:
                        - '8080:8080'
                        - '50051:50051'
                env_file:
                        - .env
                command: ["sh", "wait-for-db", "db", "./assessment"]
volumes:
        db:
