version: '3.9'

services:
        db:
                image: postgres:14-alpine
                volumes:
                        - db:/var/lib/postgresql/data
                        - ./infrastructure/db/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
                env_file:
                        - .env

        web:
                build: .
                depends_on:
                        - db
                ports:
                        - '8080:8080'
                env_file:
                        - .env
volumes:
        db:
